name: Run 100like Register & Trial

on:
  workflow_dispatch:  # Chạy manual
  # schedule:
  #   - cron: '0 0 * * *'  # Mỗi ngày lúc 0h UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python 100like/register_and_trial.py

      - name: Commit passwords.txt nếu thay đổi
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add 100like/passwords.txt
          git commit -m "Update passwords after run" || echo "No changes"
          git push || echo "No push needed"
